/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./../src/components/app/header.vue')['default']
    AppHeaderTools: typeof import('./../src/components/app/header-tools.vue')['default']
    AppLayout: typeof import('./../src/components/app/layout.vue')['default']
    AppMenuList: typeof import('./../src/components/app/menu-list.vue')['default']
    AppNavMain: typeof import('./../src/components/app/nav/main.vue')['default']
    AppNavMore: typeof import('./../src/components/app/nav/more.vue')['default']
    AppNavSearch: typeof import('./../src/components/app/nav/search.vue')['default']
    AppNavSort: typeof import('./../src/components/app/nav/sort.vue')['default']
    AppNavSubmore: typeof import('./../src/components/app/nav/submore.vue')['default']
    AppNavSubsystem: typeof import('./../src/components/app/nav/subsystem.vue')['default']
    AppSide: (typeof import('./../src/components/app/side.vue'))['default']
    IconOutlineArrowDown: typeof import('./../src/components/icon/outline-arrow-down.vue')['default']
    IconOutlineArrowLeft: typeof import('./../src/components/icon/outline-arrow-left.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusLoading: typeof import('./../src/components/status/loading.vue')['default']
    StatusMatchError: typeof import('./../src/components/status/match-error.vue')['default']
  }
}
